<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'ArcanistCheckstyleLinter' => 'lint/linter/JavaCheckstyleLinter.php',
    'ArcanistESLintLinter' => 'lint/linter/ESLintLinter.php',
    'ArcanistSassLinter' => 'lint/linter/SassLinter.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'ArcanistCheckstyleLinter' => 'ArcanistExternalLinter',
    'ArcanistESLintLinter' => 'ArcanistExternalLinter',
    'ArcanistSassLinter' => 'ArcanistExternalLinter',
  ),
));
